################################################################################
# Copyrights © 2021-2022 Fiserv, Inc. or its affiliates. 
# Fiserv is a trademark of Fiserv, Inc., 
# registered or used in the United States and foreign countries, 
# and may or may not be registered in your country.  
# All trademarks, service marks, 
# and trade names referenced in this 
# material are the property of their 
# respective owners. This work, including its contents 
# and programming, is confidential and its use 
# is strictly limited. This work is furnished only 
# for use by duly authorized licensees of Fiserv, Inc. 
# or its affiliates, and their designated agents 
# or employees responsible for installation or 
# operation of the products. Any other use, 
# duplication, or dissemination without the 
# prior written consent of Fiserv, Inc. 
# or its affiliates is strictly prohibited. 
# Except as specified by the agreement under 
# which the materials are furnished, Fiserv, Inc. 
# and its affiliates do not accept any liabilities 
# with respect to the information contained herein 
# and are not responsible for any direct, indirect, 
# special, consequential or exemplary damages 
# resulting from the use of this information. 
# No warranties, either express or implied, 
# are granted or extended by this work or 
# the delivery of this work
################################################################################
header:
  productName: BillPay
  productionDescription: Bill Pay delivers compelling bill payment experiences in an increasingly competitive space and make it easy for consumers to pay bills and receive and view their bills electronically
  whoIsItFor:  Provide small businesses with a comprehensive bill pay solution.
getStarted: /docs/getting-started.md
benefits:
  - title: Bill Discovery
    description:  Find bills by using information from credit report and biller statements with the consumer’s consent and select to add payees conveniently.
  - title: eBills
    description: Sign up for eBills from eBill capable billers to receive a full eBill statement.
  - title: Automatic Payments
    description: Automate payments and never be late with a payment again.
#steps:  
#  learnSteps:
#    - title: Learn
#      description: >
#        Follow our documentation and easy to use examples to build your own mobile or web integrated online applications. 
#      link:
#  buildSteps:
#    - title: Build
#      description: >
#        Get your application up and running with our proprietary integration tools and developer keys. 
#      link:
#  validateSteps:
#    - title: API Explorer
#      description: >
#        Interact with our live api interface for real time responses to the developed application. 
#      link:
#  deploySteps:
#    - title: Deploy
#      description: >
#        Deploy your applications in our testing environment for quality assurance testing.  Once ready promote your application to our production environment. 
#      link:
featuredFeatures:
  - title: Enrollment
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: Getting Started
        link: docs/introduction/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: BillPay APIs
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: Getting Started
        link: docs/introduction/getting-started.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: BillPay UI
    featured: true
    relatedDocs:
      - relatedDoc: 
        title: Overview
        link: docs/introduction/overview.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 1
    groupName: Group 1
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 2
    groupName: Group 1
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 3
    groupName: Group 1
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 1
    groupName: Group 2
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 2
    groupName: Group 2
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 3
    groupName: Group 2
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 1
    groupName: Group 3
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 2
    groupName: Group 3
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"
  - title: Gary Test 3
    groupName: Group 3
    featured: false
    relatedDocs:
      - relatedDoc: 
        title: Account Management
        description: Allows management of an accounts that holds financial information of Credit available/ used.
        link: ./docs/Account-Management.md
    relatedAPIs:
      - relatedAPI: 
        title: Block-Unblock Account
        description: This service is used to update the Account Block Code.
        type: "patch"        
        path: "/v1/accounts/blockUnblock"

